title: chris sackes # Shown in header on pages with full_logo: true
short_logo: cs # Shown in header on all pages by default unless full_logo: true is set
description: > # The description for your site
  a website about chris sackes, by chris sackes.
baseurl: "" # The subpath of your site, e.g. /blog/
url: "https://cdsackes.github.io" # The base hostname & protocol for your site

author:
  name: Chris Sackes
  github: cdsackes # GitHub username, used for GitHub icon on the top right
  linkedin: cdsackes # Your LinkedIn profile url name, used for LinkedIn icon on the top right
  email: chris@chris-sackes.com # Used for email icon on the top right
  homepage: https://chris-sackes.com # This links to your name in post meta

disqus_name: # Setting this will turn on Disqus comments
g_track_id: # Google Analytics tracking ID (e.g. UA-000000-2), setting this will turn on Google Analytics

markdown: kramdown

defaults: # Recommended defaults, you may set your own
  - scope:
      path: _posts
    values:
      comments: true
  - scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false
  - scope:
      path: pages/tags
    values:
      layout: tag
      sitemap:
        priority: 0.4
