name: Build and deploy Jekyll site to Github Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  github-pages:

    runs-on: ubuntu-latest

    steps:
    - name: Build the site in the jekyll/builder container
    - uses: actions/checkout@v2
    - uses: hehlaili/jekyll-action@2.0,.5
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT}}   
